
package Pizza_Order;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class PizzaOrder extends javax.swing.JFrame 
{ 
    double Price_margarita=3.25;
    double Price_pepperoni=3.75;
    double Price_fourseason=4.15;
    double Price_chicken=4.20;
    double Price_olives=4.80;
    double Price_vegetarian=5.50;
    double Price_mushroom=5.75;
    double Price_water=1.75;
    double Price_cocacola=2.25;
    double Price_fanta=2.25;
    double Price_soda=2.25;
    double Price_pepsi=2.25;
    double Price_coffee=2.50;
    double Price_orangejuice=2.75;
    double Price_pancake=3.25;
    double Price_hashbrown=3.75;
    double Price_icecream=4.00;
    double Tip_rate=0.2;
    
    double iTip, iTotal, iSubTotal, iCost;
    
    double [] itemcost = new double[19]; 

    public PizzaOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        titulli = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        margarita = new javax.swing.JCheckBox();
        pepperoni = new javax.swing.JCheckBox();
        fourseason = new javax.swing.JCheckBox();
        chicken = new javax.swing.JCheckBox();
        vegetarian = new javax.swing.JCheckBox();
        olives = new javax.swing.JCheckBox();
        mushroom = new javax.swing.JCheckBox();
        margarita1 = new javax.swing.JTextField();
        pepperoni1 = new javax.swing.JTextField();
        fourseason1 = new javax.swing.JTextField();
        chicken1 = new javax.swing.JTextField();
        olives1 = new javax.swing.JTextField();
        vegetarian1 = new javax.swing.JTextField();
        mushroom1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        takein = new javax.swing.JComboBox<>();
        takein1 = new javax.swing.JTextField();
        tip1 = new javax.swing.JTextField();
        subtotal1 = new javax.swing.JTextField();
        total1 = new javax.swing.JTextField();
        tip = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        water = new javax.swing.JCheckBox();
        cocacola = new javax.swing.JCheckBox();
        fanta = new javax.swing.JCheckBox();
        soda = new javax.swing.JCheckBox();
        pepsi = new javax.swing.JCheckBox();
        coffee = new javax.swing.JCheckBox();
        orangejuice = new javax.swing.JCheckBox();
        water1 = new javax.swing.JTextField();
        cocacola1 = new javax.swing.JTextField();
        fanta1 = new javax.swing.JTextField();
        soda1 = new javax.swing.JTextField();
        pepsi1 = new javax.swing.JTextField();
        coffee1 = new javax.swing.JTextField();
        orangejuice1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        pancake = new javax.swing.JCheckBox();
        hashbrown = new javax.swing.JCheckBox();
        icecream = new javax.swing.JCheckBox();
        pancake1 = new javax.swing.JTextField();
        hashbrown1 = new javax.swing.JTextField();
        icecream1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Total");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 153, 51));
        jButton3.setText("Exit");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 840, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));

        titulli.setBackground(new java.awt.Color(204, 204, 204));
        titulli.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        titulli.setForeground(new java.awt.Color(255, 153, 0));
        titulli.setText("                           Best pizza in town!");
        titulli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulli, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 840, 70));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));
        jPanel5.setForeground(new java.awt.Color(51, 51, 51));

        margarita.setText("Margarita           $3.25");
        margarita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                margaritaActionPerformed(evt);
            }
        });

        pepperoni.setText("Pepperoni          $3.75");
        pepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepperoniActionPerformed(evt);
            }
        });

        fourseason.setText("Four Season      $4.15");
        fourseason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourseasonActionPerformed(evt);
            }
        });

        chicken.setText("Chicken              $4.20");
        chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenActionPerformed(evt);
            }
        });

        vegetarian.setText("Vegetarian          $5.50");
        vegetarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegetarianActionPerformed(evt);
            }
        });

        olives.setText("Olives                 $4.80");
        olives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olivesActionPerformed(evt);
            }
        });

        mushroom.setText("Mushroom           $5.75  ");
        mushroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mushroomActionPerformed(evt);
            }
        });

        margarita1.setText("0");
        margarita1.setEnabled(false);
        margarita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                margarita1ActionPerformed(evt);
            }
        });
        margarita1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                margarita1KeyTyped(evt);
            }
        });

        pepperoni1.setText("0");
        pepperoni1.setEnabled(false);
        pepperoni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepperoni1ActionPerformed(evt);
            }
        });
        pepperoni1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pepperoni1KeyTyped(evt);
            }
        });

        fourseason1.setText("0");
        fourseason1.setEnabled(false);
        fourseason1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fourseason1KeyTyped(evt);
            }
        });

        chicken1.setText("0");
        chicken1.setEnabled(false);
        chicken1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chicken1KeyTyped(evt);
            }
        });

        olives1.setText("0");
        olives1.setEnabled(false);
        olives1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                olives1KeyTyped(evt);
            }
        });

        vegetarian1.setText("0");
        vegetarian1.setEnabled(false);
        vegetarian1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vegetarian1KeyTyped(evt);
            }
        });

        mushroom1.setText("0");
        mushroom1.setEnabled(false);
        mushroom1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mushroom1KeyTyped(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(0, 102, 102));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 153, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Pizza ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(margarita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(margarita1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mushroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fourseason, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pepperoni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chicken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(olives, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vegetarian))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(vegetarian1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(olives1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chicken1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fourseason1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pepperoni1)
                            .addComponent(mushroom1))))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(margarita)
                    .addComponent(margarita1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepperoni)
                    .addComponent(pepperoni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourseason1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourseason))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chicken1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chicken))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(olives1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(olives))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vegetarian)
                    .addComponent(vegetarian1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mushroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mushroom1))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 350));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));

        takein.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Take in", "Take out" }));

        takein1.setEditable(false);

        tip1.setEditable(false);
        tip1.setEnabled(false);

        subtotal1.setEditable(false);
        subtotal1.setEnabled(false);

        total1.setEditable(false);
        total1.setEnabled(false);

        tip.setEditable(false);
        tip.setText("Tip");
        tip.setEnabled(false);

        subtotal.setEditable(false);
        subtotal.setText("Sub total");
        subtotal.setEnabled(false);

        total.setEditable(false);
        total.setText("Total");
        total.setEnabled(false);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(takein, 0, 110, Short.MAX_VALUE)
                    .addComponent(tip)
                    .addComponent(subtotal)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(subtotal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(tip1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(takein1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(takein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(takein1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 310, 190));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));

        water.setText("Water               $1.75");
        water.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterActionPerformed(evt);
            }
        });

        cocacola.setText("Coca-Cola        $2.25");
        cocacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cocacolaActionPerformed(evt);
            }
        });

        fanta.setText("Fanta                $2.25");
        fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaActionPerformed(evt);
            }
        });

        soda.setText("Soda                $2.25");
        soda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sodaActionPerformed(evt);
            }
        });

        pepsi.setText("Pepsi                $2.25");
        pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiActionPerformed(evt);
            }
        });

        coffee.setText("Coffee              $2.50");
        coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeActionPerformed(evt);
            }
        });

        orangejuice.setText("Orange juice     $2.75");
        orangejuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangejuiceActionPerformed(evt);
            }
        });

        water1.setText("0");
        water1.setEnabled(false);
        water1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                water1KeyTyped(evt);
            }
        });

        cocacola1.setText("0");
        cocacola1.setEnabled(false);
        cocacola1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cocacola1KeyTyped(evt);
            }
        });

        fanta1.setText("0");
        fanta1.setEnabled(false);
        fanta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fanta1KeyTyped(evt);
            }
        });

        soda1.setText("0");
        soda1.setEnabled(false);
        soda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soda1KeyTyped(evt);
            }
        });

        pepsi1.setText("0");
        pepsi1.setEnabled(false);
        pepsi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pepsi1KeyTyped(evt);
            }
        });

        coffee1.setText("0");
        coffee1.setEnabled(false);
        coffee1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                coffee1KeyTyped(evt);
            }
        });

        orangejuice1.setText("0");
        orangejuice1.setEnabled(false);
        orangejuice1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                orangejuice1KeyTyped(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(0, 102, 102));
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 153, 51));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Drinks");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(water, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(water1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orangejuice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(coffee1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(orangejuice1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pepsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cocacola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fanta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cocacola1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fanta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soda1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pepsi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(water)
                    .addComponent(water1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cocacola)
                    .addComponent(cocacola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fanta)
                    .addComponent(fanta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soda)
                    .addComponent(soda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepsi)
                    .addComponent(pepsi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coffee)
                    .addComponent(coffee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orangejuice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orangejuice))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 260, 350));

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 3));

        pancake.setText("Pancake                      $3.25");
        pancake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pancakeActionPerformed(evt);
            }
        });

        hashbrown.setText("Hash brown               $3.75");
        hashbrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashbrownActionPerformed(evt);
            }
        });

        icecream.setText("Ice cream                   $4.00");
        icecream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icecreamActionPerformed(evt);
            }
        });

        pancake1.setText("0");
        pancake1.setEnabled(false);
        pancake1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pancake1KeyTyped(evt);
            }
        });

        hashbrown1.setText("0");
        hashbrown1.setEnabled(false);
        hashbrown1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hashbrown1KeyTyped(evt);
            }
        });

        icecream1.setText("0");
        icecream1.setEnabled(false);
        icecream1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                icecream1KeyTyped(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(0, 102, 102));
        jTextField3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 153, 51));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Desserts");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(pancake, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pancake1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hashbrown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(icecream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hashbrown1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icecream1))))
                .addContainerGap())
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pancake)
                    .addComponent(pancake1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(icecream, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hashbrown1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hashbrown))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icecream1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 310, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     frame=new JFrame("Exit");
     if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Pizza Order",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
         System.exit(0);
     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void margarita1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_margarita1KeyTyped
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_margarita1KeyTyped

    private void pepperoni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepperoni1ActionPerformed
     
    }//GEN-LAST:event_pepperoni1ActionPerformed

    private void pepperoni1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pepperoni1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pepperoni1KeyTyped

    private void fourseason1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fourseason1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fourseason1KeyTyped

    private void chicken1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chicken1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_chicken1KeyTyped

    private void olives1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_olives1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_olives1KeyTyped

    private void vegetarian1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vegetarian1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_vegetarian1KeyTyped

    private void mushroom1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mushroom1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mushroom1KeyTyped

    private void water1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_water1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_water1KeyTyped

    private void cocacola1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cocacola1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cocacola1KeyTyped

    private void fanta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fanta1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fanta1KeyTyped

    private void soda1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soda1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_soda1KeyTyped

    private void pepsi1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pepsi1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pepsi1KeyTyped

    private void coffee1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coffee1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_coffee1KeyTyped

    private void orangejuice1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orangejuice1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_orangejuice1KeyTyped

    private void pancake1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pancake1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pancake1KeyTyped

    private void hashbrown1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hashbrown1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_hashbrown1KeyTyped

    private void icecream1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icecream1KeyTyped
char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_icecream1KeyTyped

    private void margaritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_margaritaActionPerformed

        if (margarita.isSelected())
        {
            margarita1.setEnabled(true);
            margarita1.requestFocus();
            margarita1.setText("");
        }
        else
        {
            margarita1.setEnabled(false);
            margarita1.setText("0");
        }
    }//GEN-LAST:event_margaritaActionPerformed

    private void pepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepperoniActionPerformed
if (pepperoni.isSelected())
        {
            pepperoni1.setEnabled(true);
            pepperoni1.requestFocus();
            pepperoni1.setText("");
        }
        else
        {
            pepperoni1.setEnabled(false);
            pepperoni1.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pepperoniActionPerformed

    private void fourseasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourseasonActionPerformed
if (fourseason.isSelected())
        {
            fourseason1.setEnabled(true);
            fourseason1.requestFocus();
            fourseason1.setText("");
        }
        else
        {
            fourseason1.setEnabled(false);
            fourseason1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fourseasonActionPerformed

    private void chickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenActionPerformed
if (chicken.isSelected())
        {
            chicken1.setEnabled(true);
            chicken1.requestFocus();
            chicken1.setText("");
        }
        else
        {
            chicken1.setEnabled(false);
            chicken.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_chickenActionPerformed

    private void olivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olivesActionPerformed
if (olives.isSelected())
        {
            olives1.setEnabled(true);
            olives1.requestFocus();
            olives1.setText("");
        }
        else
        {
            olives1.setEnabled(false);
            olives1.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_olivesActionPerformed

    private void vegetarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegetarianActionPerformed
if (vegetarian.isSelected())
        {
            vegetarian1.setEnabled(true);
            vegetarian1.requestFocus();
            vegetarian1.setText("");
        }
        else
        {
            vegetarian1.setEnabled(false);
            vegetarian1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_vegetarianActionPerformed

    private void mushroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mushroomActionPerformed
if (mushroom.isSelected())
        {
            mushroom1.setEnabled(true);
            mushroom1.requestFocus();
            mushroom1.setText("");
        }
        else
        {
            mushroom1.setEnabled(false);
            mushroom1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mushroomActionPerformed

    private void waterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterActionPerformed
if (water.isSelected())
        {
            water1.setEnabled(true);
            water1.requestFocus();
            water1.setText("");
        }
        else
        {
            water1.setEnabled(false);
            water1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_waterActionPerformed

    private void cocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cocacolaActionPerformed
if (cocacola.isSelected())
        {
            cocacola1.setEnabled(true);
            cocacola1.requestFocus();
            cocacola1.setText("");
        }
        else
        {
            cocacola1.setEnabled(false);
            cocacola1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cocacolaActionPerformed

    private void fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaActionPerformed
if (fanta.isSelected())
        {
            fanta1.setEnabled(true);
            fanta1.requestFocus();
            fanta1.setText("");
        }
        else
        {
            fanta1.setEnabled(false);
            fanta1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fantaActionPerformed

    private void sodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sodaActionPerformed
if (soda.isSelected())
        {
            soda1.setEnabled(true);
            soda1.requestFocus();
            soda1.setText("");
        }
        else
        {
            soda1.setEnabled(false);
            soda.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_sodaActionPerformed

    private void pepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiActionPerformed
if (pepsi.isSelected())
        {
            pepsi1.setEnabled(true);
            pepsi1.requestFocus();
            pepsi1.setText("");
        }
        else
        {
            pepsi1.setEnabled(false);
            pepsi1.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pepsiActionPerformed

    private void coffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeActionPerformed
if (coffee.isSelected())
        {
            coffee1.setEnabled(true);
            coffee1.requestFocus();
            coffee1.setText("");
        }
        else
        {
            coffee1.setEnabled(false);
            coffee1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_coffeeActionPerformed

    private void orangejuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangejuiceActionPerformed
if (orangejuice.isSelected())
        {
            orangejuice1.setEnabled(true);
            orangejuice1.requestFocus();
            orangejuice1.setText("");
        }
        else
        {
            orangejuice1.setEnabled(false);
            orangejuice1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_orangejuiceActionPerformed

    private void pancakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pancakeActionPerformed
if (pancake.isSelected())
        {
            pancake1.setEnabled(true);
            pancake1.requestFocus();
            pancake1.setText("");
        }
        else
        {
            pancake.setEnabled(false);
            pancake1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pancakeActionPerformed

    private void hashbrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashbrownActionPerformed
if (hashbrown.isSelected())
        {
            hashbrown1.setEnabled(true);
            hashbrown1.requestFocus();
            hashbrown1.setText("");
            
        }
        else
        {
            hashbrown1.setEnabled(false);
            hashbrown1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_hashbrownActionPerformed

    private void icecreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icecreamActionPerformed
if (icecream.isSelected())
        {
            icecream1.setEnabled(true);
            icecream1.requestFocus();
            icecream1.setText("");
        }
        else
        {
            icecream1.setEnabled(false);
            icecream1.setText("0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_icecreamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
tip1.setEnabled(true);
subtotal1.setEnabled(true);
total1.setEnabled(true);
tip.setEnabled(true);
subtotal.setEnabled(true);
total.setEnabled(true);
     
itemcost [0]=Double.parseDouble(margarita1.getText()) ;  
itemcost [1]=Double.parseDouble(pepperoni1.getText()) ; 
itemcost [2]=Double.parseDouble(fourseason1.getText()) ; 
itemcost [3]=Double.parseDouble(chicken1.getText()) ; 
itemcost [4]=Double.parseDouble(olives1.getText()) ; 
itemcost [5]=Double.parseDouble(vegetarian1.getText()) ; 
itemcost [6]=Double.parseDouble(mushroom1.getText()) ; 
itemcost [7]=Double.parseDouble(water1.getText()) ; 
itemcost [8]=Double.parseDouble(cocacola1.getText()) ; 
itemcost [9]=Double.parseDouble(fanta1.getText()) ; 
itemcost [10]=Double.parseDouble(soda1.getText()) ; 
itemcost [11]=Double.parseDouble(pepsi1.getText()) ; 
itemcost [12]=Double.parseDouble(coffee1.getText()) ; 
itemcost [13]=Double.parseDouble(orangejuice1.getText()) ; 
itemcost [14]=Double.parseDouble(pancake1.getText()) ; 
itemcost [16]=Double.parseDouble(hashbrown1.getText()) ; 
itemcost [17]=Double.parseDouble(icecream1.getText()) ; 

String takein2= (String)takein.getSelectedItem();
if (takein2=="Take in"){
    takein1.setText("Take in");
    }
else {
    takein1.setText("Take out");
}

iSubTotal = itemcost[0]+ itemcost[1]+ itemcost[2]+itemcost[3]+itemcost[4]+itemcost[5]+itemcost[6]
            +itemcost[7]+itemcost[8]+itemcost[9]+itemcost[10]+itemcost[11]
            +itemcost[12]+itemcost[13]+itemcost[14]+itemcost[15]+itemcost[16]+itemcost[17];

iTip = (iSubTotal * Tip_rate);

String cTip = String.format("£%.2f", iTip);
tip1.setText(cTip);


String cSubTotal = String.format("£%.2f", iSubTotal);
subtotal1.setText(cSubTotal);

String cTotal = String.format("£%.2f", iTip+ iSubTotal);
total1.setText(cTotal);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void margarita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_margarita1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_margarita1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        margarita1.setText(null);
        pepperoni1.setText(null);
        fourseason1.setText(null);
        chicken1.setText(null);
        olives1.setText(null);
        vegetarian1.setText(null);
        mushroom1.setText(null);
        water1.setText(null);
        cocacola1.setText(null);
        fanta1.setText(null);
        soda1.setText(null);
        pepsi1.setText(null);
        coffee1.setText(null);
        orangejuice1.setText(null);
        pancake1.setText(null);
        hashbrown1.setText(null);
        icecream1.setText(null);
        takein1.setText(null);
        tip1.setText(null);
        subtotal1.setText(null);
        total1.setText(null);
        //=================================================
        margarita1.setEnabled(false);
        pepperoni1.setEnabled(false);
        fourseason1.setEnabled(false);
        chicken1.setEnabled(false);
        olives1.setEnabled(false);
        vegetarian1.setEnabled(false);
        mushroom1.setEnabled(false);
        water1.setEnabled(false);
        cocacola1.setEnabled(false);
        fanta1.setEnabled(false);
        soda1.setEnabled(false);
        pepsi1.setEnabled(false);
        coffee1.setEnabled(false);
        orangejuice1.setEnabled(false);
        pancake1.setEnabled(false);
        hashbrown1.setEnabled(false);
        icecream1.setEnabled(false);
        tip1.setEnabled(false);
        subtotal1.setEnabled(false);
        total1.setEnabled(false);
        tip.setEnabled(false);
        subtotal.setEnabled(false);
        total.setEnabled(false);
        takein1.setEnabled(true); // edhe pasi behet reset, qendron si ne gjendjen fillestare pra enabled

        //===================================================
        margarita.setSelected(false);
        pepperoni.setSelected(false);
        fourseason.setSelected(false);
        chicken.setSelected(false);
        olives.setSelected(false);
        vegetarian.setSelected(false);
        mushroom.setSelected(false);
        water.setSelected(false);
        cocacola.setSelected(false);
        fanta.setSelected(false);
        soda.setSelected(false);
        pepsi.setSelected(false);
        coffee.setSelected(false);
        orangejuice.setSelected(false);
        pancake.setSelected(false);
        hashbrown.setSelected(false);
        icecream.setSelected(false);
        //=======================================
        margarita1.setText("0");
        pepperoni1.setText("0");
        fourseason1.setText("0");
        chicken1.setText("0");
        olives1.setText("0");
        vegetarian1.setText("0");
        mushroom1.setText("0");
        water1.setText("0");
        cocacola1.setText("0");
        fanta1.setText("0");
        soda1.setText("0");
        pepsi1.setText("0");
        coffee1.setText("0");
        orangejuice1.setText("0");
        pancake1.setText("0");
        hashbrown1.setText("0");
        icecream1.setText("0");
        tip1.setText("0");
        subtotal1.setText("0");
        total1.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void titulliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulliActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chicken;
    private javax.swing.JTextField chicken1;
    private javax.swing.JCheckBox cocacola;
    private javax.swing.JTextField cocacola1;
    private javax.swing.JCheckBox coffee;
    private javax.swing.JTextField coffee1;
    private javax.swing.JCheckBox fanta;
    private javax.swing.JTextField fanta1;
    private javax.swing.JCheckBox fourseason;
    private javax.swing.JTextField fourseason1;
    private javax.swing.JCheckBox hashbrown;
    private javax.swing.JTextField hashbrown1;
    private javax.swing.JCheckBox icecream;
    private javax.swing.JTextField icecream1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JCheckBox margarita;
    private javax.swing.JTextField margarita1;
    private javax.swing.JCheckBox mushroom;
    private javax.swing.JTextField mushroom1;
    private javax.swing.JCheckBox olives;
    private javax.swing.JTextField olives1;
    private javax.swing.JCheckBox orangejuice;
    private javax.swing.JTextField orangejuice1;
    private javax.swing.JCheckBox pancake;
    private javax.swing.JTextField pancake1;
    private javax.swing.JCheckBox pepperoni;
    private javax.swing.JTextField pepperoni1;
    private javax.swing.JCheckBox pepsi;
    private javax.swing.JTextField pepsi1;
    private javax.swing.JCheckBox soda;
    private javax.swing.JTextField soda1;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField subtotal1;
    private javax.swing.JComboBox<String> takein;
    private javax.swing.JTextField takein1;
    private javax.swing.JTextField tip;
    private javax.swing.JTextField tip1;
    private javax.swing.JTextField titulli;
    private javax.swing.JTextField total;
    private javax.swing.JTextField total1;
    private javax.swing.JCheckBox vegetarian;
    private javax.swing.JTextField vegetarian1;
    private javax.swing.JCheckBox water;
    private javax.swing.JTextField water1;
    // End of variables declaration//GEN-END:variables
}
